version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/my-app/
permissions:
  - object: /home/ubuntu
    owner: ubuntu
    group: ubuntu
hooks:
  BeforeInstall:
    - location: scripts/backup.sh
      runas: ubuntu
  AfterInstall:
    - location: scripts/install-dependencies.sh
      runas: ubuntu
  ApplicationStart:
    - location: scripts/start.sh
    - location: scripts/cleanup.sh
      runas: ubuntu
