version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/my-app/
hooks:
  BeforeInstall:
    - location: scripts/backup.sh
  AfterInstall:
    - location: scripts/install-dependencies.sh
  ApplicationStart:
    - location: /home/ubuntu/test.sh
    - location: scripts/cleanup.sh
