version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/my-app/
permissions:
  - object: /home/ubuntu
    owner: ubuntu
    group: ubuntu
permissions:
  - object: .
    owner: ubuntu
    group: ubuntu
hooks:
  BeforeInstall:
    - location: scripts/backup.sh
  AfterInstall:
    - location: scripts/install-dependencies.sh
  ApplicationStart:
    - location: scripts/start.sh
      runsas: ubuntu
#    - location: scripts/cleanup.sh
